pipeline {
    agent none
    stages {
        stage('Build') {
            agent { 
                docker {
                    image 'maven:3.5.4-alpine'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'ls -lrt'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            agent { 
                docker {
                    image 'maven:3.5.4-alpine'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                 sh 'ls -lrt'
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('sonar') {
            agent { 
                docker {
                    image 'sonarsource/sonar-scanner-cli:latest'
                    }
            }
            steps {
                 sh 'ls -lrt'
                sh 'sonar-scanner -Dsonar.login=45bedaabeed2cf14ba8cb5926b2a05a1c5511e20'
            }
        } 
        stage('Docker Build') {
            agent { 
                docker {
                    image 'docker'
                    }
            }
            steps {
                 sh 'ls -lrt'
                 sh ''' 
                    echo $workspace
                    ls -lrt
                    docker build -t test .
                    '''

                }
        } 
    }
}
